pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    // Меняем строгий режим FAIL_ON_PROJECT_REPOS на более мягкий, чтобы модули могли сами докачивать библиотеки
    repositoriesMode.set(RepositoriesMode.PRESERVE_ON_USE)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "LibertyVPN"
include ':app'
